inherit_from:
  - https://potpourri.hausgold.de/config/rubocop.yml
  - https://potpourri.hausgold.de/config/rubocop-gem.yml

inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-rspec
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  SuggestExtensions: false
  DisplayCopNames: true
  TargetRubyVersion: 3.3
  TargetRailsVersion: 7.2
  Exclude:
    - bin/**/*
    - vendor/**/*
    - config/**/*
    - build/**/*
    - gemfiles/**/*
