inherit_from:
  - https://potpourri.hausgold.de/config/rubocop.yml
  - https://potpourri.hausgold.de/config/rubocop-gem.yml

plugins:
  - rubocop-rspec
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  SuggestExtensions: false
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  TargetRailsVersion: 7.1
  Exclude:
    - bin/**/*
    - vendor/**/*
    - config/**/*
    - build/**/*
    - gemfiles/**/*
