version: "3"
services:
  jabber:
    image: hausgold/ejabberd:18.01
    network_mode: bridge
    ports: ["4560", "5222", "5269", "5280", "5443"]

  test:
    build: .
    env_file: Envfile
    network_mode: bridge
    working_dir: /app
    volumes:
      - .:/app
    links:
      - jabber
