name: Test
on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * MON'

concurrency:
  group: '${{ github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    name: 'Test the gem (Ruby ${{ matrix.ruby }})'
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7]
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    steps:
      - uses: actions/checkout@v2

      - name: Install the correct Ruby version
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Prepare the virtual environment
        uses: hausgold/actions/ci@master
        with:
          clone_token: '${{ secrets.CLONE_TOKEN }}'
          settings: '${{ github.repository }}'
          target: ci/gem-test

      - name: Run the gem tests
        run: bundle exec rspec

      - name: Upload the code coverage report
        run: codeclimate
